/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#4f46e5",
        "error": "#ffb4ab",
        "tertiary-container": "#a44100",
        "inverse-primary": "#4d44e3",
        "on-error": "#690005",
        "surface-container-high": "#1b2b3f",
        "surface": "#031427",
        "on-secondary-container": "#b0b2ff",
        "inverse-on-surface": "#213145",
        "surface-container-low": "#0b1c30",
        "on-secondary-fixed": "#07006c",
        "on-tertiary": "#571f00",
        "surface-container-lowest": "#000f21",
        "tertiary": "#ffb695",
        "on-tertiary-fixed": "#351000",
        "on-error-container": "#ffdad6",
        "secondary": "#c0c1ff",
        "outline-variant": "#464555",
        "primary-fixed": "#e2dfff",
        "primary": "#c3c0ff",
        "surface-dim": "#031427",
        "secondary-container": "#3131c0",
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#26364a",
        "on-tertiary-container": "#ffd2be",
        "primary-fixed-dim": "#c3c0ff",
        "surface-bright": "#2a3a4f",
        "surface-variant": "#26364a",
        "on-primary-fixed": "#0f0069",
        "on-background": "#d3e4fe",
        "on-primary": "#1d00a5",
        "outline": "#918fa1",
        "on-primary-fixed-variant": "#3323cc",
        "surface-tint": "#c3c0ff",
        "secondary-fixed": "#e1e0ff",
        "background": "#031427",
        "tertiary-fixed-dim": "#ffb695",
        "on-secondary": "#1000a9",
        "tertiary-fixed": "#ffdbcc",
        "surface-container": "#102034",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-surface": "#d3e4fe",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#d3e4fe",
        "on-surface-variant": "#c7c4d8",
        "level-0": "#0B0E14",
        "level-1": "#151921",
        "level-2": "#1C212B",
        "border-color": "#2D333B",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "24px"
      },
      fontFamily: {
        "sans": ["Geist", "Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        'pulse-glow': 'pulse-glow 4s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      }
    },
  },
  plugins: [],
}
