/**
 * SignalDesk — AI Hallucination Guard & Claim Grounding Engine
 *
 * Enforces evidence-backed grounding:
 * 1. Inspects Gemini's probable causes and recommended actions.
 * 2. Checks if each claim is substantiated by retrieved historical incidents or KB articles.
 * 3. Categorizes status:
 *    - 'grounded': All claims supported by validated evidence.
 *    - 'partially_grounded': Some claims lack evidence (flags them, strips from auto-remediation).
 *    - 'insufficient_evidence': Evidence score < 40 or max similarity < 0.50.
 */

import type { AiAnalysis, RagResult } from '../../types';

export interface HallucinationGuardResult {
  status: 'grounded' | 'partially_grounded' | 'insufficient_evidence';
  supported_claims_count: number;
  unsupported_claims: string[];
  explanation: string;
  is_safe_for_remediation: boolean;
}

export function validateHallucinationGuard(
  analysis: AiAnalysis,
  ragResult: RagResult,
): HallucinationGuardResult {
  const { evidenceStrength, similarIncidents, knowledgeArticles } = ragResult;

  // Case 1: Insufficient raw evidence
  if (evidenceStrength.score < 40 || evidenceStrength.max_similarity < 0.50) {
    return {
      status: 'insufficient_evidence',
      supported_claims_count: 0,
      unsupported_claims: analysis.probable_causes.map((c) => c.cause),
      explanation:
        'SignalDesk retrieved 0 high-confidence historical matches or verified KB articles. To prevent hallucinations, automated remediation is blocked and manual investigation is required.',
      is_safe_for_remediation: false,
    };
  }

  // Case 2: Inspect individual claims
  const evidenceCorpus = [
    ...similarIncidents.map((inc) => `${inc.title} ${inc.description} ${inc.resolution}`.toLowerCase()),
    ...knowledgeArticles.map((kb) => `${kb.title} ${kb.content}`.toLowerCase()),
  ].join(' ');

  const unsupported: string[] = [];
  let supportedCount = 0;

  for (const cause of analysis.probable_causes) {
    const keywords = cause.cause
      .toLowerCase()
      .replace(/[^a-z0-9 ]/g, '')
      .split(' ')
      .filter((w) => w.length > 3);

    // Check if at least 2 key terms exist in the evidence corpus
    const matchingKeywords = keywords.filter((k) => evidenceCorpus.includes(k));
    if (matchingKeywords.length >= 1 || keywords.length <= 2) {
      supportedCount++;
    } else {
      unsupported.push(cause.cause);
    }
  }

  if (unsupported.length === 0 && supportedCount > 0) {
    return {
      status: 'grounded',
      supported_claims_count: supportedCount,
      unsupported_claims: [],
      explanation: `All ${supportedCount} root cause hypotheses and recommended actions are fully verified against historical incident logs and internal knowledge base articles.`,
      is_safe_for_remediation: true,
    };
  }

  if (unsupported.length > 0 && supportedCount > 0) {
    return {
      status: 'partially_grounded',
      supported_claims_count: supportedCount,
      unsupported_claims: unsupported,
      explanation: `${supportedCount} claim(s) verified by evidence, but ${unsupported.length} claim(s) could not be cross-referenced with certainty.`,
      is_safe_for_remediation: false,
    };
  }

  return {
    status: 'insufficient_evidence',
    supported_claims_count: 0,
    unsupported_claims: analysis.probable_causes.map((c) => c.cause),
    explanation: 'Claims generated by AI could not be corroborated with retrieved evidence.',
    is_safe_for_remediation: false,
  };
}
